// Command gen-client creates the browser API client from the Go-owned contract.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"rwandafreespace.com/blog/backend/internal/features/servertime"
)

func main() {
	output := flag.String("out", "src/lib/api/generated.ts", "generated TypeScript file")
	check := flag.Bool("check", false, "fail when the generated file is stale")
	flag.Parse()

	content := generate()
	if *check {
		existing, err := os.ReadFile(*output)
		if err != nil || !bytes.Equal(existing, content) {
			fmt.Fprintf(os.Stderr, "%s is stale; run make generate\n", *output)
			os.Exit(1)
		}
		return
	}

	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, content, 0o644); err != nil {
		panic(err)
	}
}

func generate() []byte {
	var output strings.Builder
	output.WriteString("// Code generated by go generate ./backend/...; DO NOT EDIT.\n\n")
	writeInterface(&output, "ServerTimeData", reflect.TypeOf(servertime.Data{}), typeNames())
	writeInterface(&output, "ServerTimeMeta", reflect.TypeOf(servertime.Meta{}), typeNames())
	writeInterface(&output, "ServerTimeResponse", reflect.TypeOf(servertime.Response{}), typeNames())
	writeInterface(&output, "APIError", reflect.TypeOf(servertime.APIError{}), typeNames())
	writeInterface(&output, "APIErrorResponse", reflect.TypeOf(servertime.ErrorResponse{}), typeNames())
	output.WriteString(strings.ReplaceAll(clientRuntime, "__SERVER_TIME_ROUTE__", servertime.Route))
	return []byte(output.String())
}

func typeNames() map[reflect.Type]string {
	return map[reflect.Type]string{
		reflect.TypeOf(servertime.Data{}):          "ServerTimeData",
		reflect.TypeOf(servertime.Meta{}):          "ServerTimeMeta",
		reflect.TypeOf(servertime.Response{}):      "ServerTimeResponse",
		reflect.TypeOf(servertime.APIError{}):      "APIError",
		reflect.TypeOf(servertime.ErrorResponse{}): "APIErrorResponse",
	}
}

func writeInterface(output *strings.Builder, name string, value reflect.Type, names map[reflect.Type]string) {
	fmt.Fprintf(output, "export interface %s {\n", name)
	for index := range value.NumField() {
		field := value.Field(index)
		jsonName := strings.Split(field.Tag.Get("json"), ",")[0]
		if jsonName == "" || jsonName == "-" {
			continue
		}
		fmt.Fprintf(output, "  %s: %s;\n", jsonName, typeScriptType(field.Type, names))
	}
	output.WriteString("}\n\n")
}

func typeScriptType(value reflect.Type, names map[reflect.Type]string) string {
	if name, ok := names[value]; ok {
		return name
	}
	switch value.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return typeScriptType(value.Elem(), names) + "[]"
	case reflect.Pointer:
		return typeScriptType(value.Elem(), names) + " | null"
	default:
		panic("unsupported contract type: " + value.String())
	}
}

const clientRuntime = `export type CacheSource = "network" | "cache" | "shared";

export interface ServerTimeResult extends ServerTimeResponse {
  client: {
    source: CacheSource;
    cachedAt: string;
    expiresAt: string;
  };
}

export interface GetServerTimeOptions {
  baseUrl?: string;
  forceRefresh?: boolean;
  ttlMs?: number;
  timeoutMs?: number;
  signal?: AbortSignal;
  fetch?: typeof fetch;
}

export class APIRequestError extends Error {
  readonly status: number;
  readonly code: string;
  readonly requestId?: string;

  constructor(message: string, status = 0, code = "request_failed", requestId?: string) {
    super(message);
    this.name = "APIRequestError";
    this.status = status;
    this.code = code;
    this.requestId = requestId;
  }
}

const SERVER_TIME_ROUTE = "__SERVER_TIME_ROUTE__";
const DEFAULT_TTL_MS = 5_000;
const DEFAULT_TIMEOUT_MS = 5_000;

interface CacheEntry {
  response: ServerTimeResponse;
  cachedAt: number;
  expiresAt: number;
}

const cache = new Map<string, CacheEntry>();
const pending = new Map<string, Promise<ServerTimeResult>>();

export async function getServerTime(options: GetServerTimeOptions = {}): Promise<ServerTimeResult> {
  const endpoint = buildEndpoint(options.baseUrl);
  const now = Date.now();
  const cached = cache.get(endpoint);

  if (!options.forceRefresh && cached && cached.expiresAt > now) {
    return withClientMetadata(cached.response, "cache", cached.cachedAt, cached.expiresAt);
  }

  if (!options.forceRefresh && !options.signal) {
    const activeRequest = pending.get(endpoint);
    if (activeRequest) {
      const result = await activeRequest;
      return { ...result, client: { ...result.client, source: "shared" } };
    }
  }

  const request = requestServerTime(endpoint, options);
  if (!options.forceRefresh && !options.signal) {
    pending.set(endpoint, request);
  }

  try {
    return await request;
  } finally {
    if (pending.get(endpoint) === request) {
      pending.delete(endpoint);
    }
  }
}

export function clearServerTimeCache(baseUrl?: string): void {
  if (baseUrl === undefined) {
    cache.clear();
    return;
  }
  cache.delete(buildEndpoint(baseUrl));
}

async function requestServerTime(endpoint: string, options: GetServerTimeOptions): Promise<ServerTimeResult> {
  const timeoutMs = positiveNumber(options.timeoutMs, DEFAULT_TIMEOUT_MS);
  const ttlMs = Math.max(0, options.ttlMs ?? DEFAULT_TTL_MS);
  const controller = new AbortController();
  const timeout = globalThis.setTimeout(() => controller.abort(new Error("request timed out")), timeoutMs);
  const onAbort = () => controller.abort(options.signal?.reason);

  if (options.signal?.aborted) {
    onAbort();
  } else {
    options.signal?.addEventListener("abort", onAbort, { once: true });
  }

  try {
    const fetcher = options.fetch ?? globalThis.fetch;
    if (!fetcher) {
      throw new APIRequestError("Fetch is not available in this environment");
    }
    const response = await fetcher(endpoint, {
      method: "GET",
      headers: { Accept: "application/json" },
      signal: controller.signal,
    });
    const payload: unknown = await response.json().catch(() => undefined);

    if (!response.ok) {
      const apiError = isAPIErrorResponse(payload) ? payload.error : undefined;
      throw new APIRequestError(
        apiError?.message ?? "API request failed with status " + response.status,
        response.status,
        apiError?.code,
        apiError?.requestId,
      );
    }
    if (!isServerTimeResponse(payload)) {
      throw new APIRequestError("The API returned an invalid server-time response", response.status, "invalid_response");
    }

    const cachedAt = Date.now();
    const expiresAt = cachedAt + ttlMs;
    cache.set(endpoint, { response: payload, cachedAt, expiresAt });
    return withClientMetadata(payload, "network", cachedAt, expiresAt);
  } catch (error) {
    if (error instanceof APIRequestError) {
      throw error;
    }
    if (controller.signal.aborted) {
      throw new APIRequestError("The server-time request was cancelled or timed out", 0, "request_aborted");
    }
    throw new APIRequestError(error instanceof Error ? error.message : "Unable to reach the API");
  } finally {
    globalThis.clearTimeout(timeout);
    options.signal?.removeEventListener("abort", onAbort);
  }
}

function buildEndpoint(baseUrl?: string): string {
  const configuredBase = baseUrl ?? import.meta.env.PUBLIC_API_BASE_URL ?? "";
  return configuredBase.replace(/\/$/, "") + SERVER_TIME_ROUTE;
}

function positiveNumber(value: number | undefined, fallback: number): number {
  return value !== undefined && Number.isFinite(value) && value > 0 ? value : fallback;
}

function withClientMetadata(response: ServerTimeResponse, source: CacheSource, cachedAt: number, expiresAt: number): ServerTimeResult {
  return {
    ...response,
    client: {
      source,
      cachedAt: new Date(cachedAt).toISOString(),
      expiresAt: new Date(expiresAt).toISOString(),
    },
  };
}

function isServerTimeResponse(value: unknown): value is ServerTimeResponse {
  if (!value || typeof value !== "object") return false;
  const response = value as Partial<ServerTimeResponse>;
  return Boolean(
    response.data &&
      typeof response.data.iso === "string" &&
      typeof response.data.display === "string" &&
      typeof response.data.timeZone === "string" &&
      typeof response.data.unixMilliseconds === "number" &&
      response.meta &&
      typeof response.meta.requestId === "string",
  );
}

function isAPIErrorResponse(value: unknown): value is APIErrorResponse {
  if (!value || typeof value !== "object") return false;
  const response = value as Partial<APIErrorResponse>;
  return Boolean(response.error && typeof response.error.code === "string" && typeof response.error.message === "string");
}
`
